version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=local-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
      - ./init-user-db.sh:./docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432
